# Generated by Django 6.1.1 on 2026-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posteo',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
