# Generated by Django 6.1.1 on 2026-09-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_agregar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220, unique=True),
        ),
    ]
