# Generated by Django 6.1.1 on 2026-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_slug_obligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Opcional. Elegí una imagen JPG, PNG o WebP.', null=True, upload_to='posts/%Y/%m/'),
        ),
    ]
